// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ghs_missing_gibbs_cpp
List ghs_missing_gibbs_cpp(const arma::mat& Y, int n_iter, int burnin, int thin, bool verbose, bool store_Z, double a0, double b0, std::string symmetrize, bool project_spd);
RcppExport SEXP _ghscenmis_ghs_missing_gibbs_cpp(SEXP YSEXP, SEXP n_iterSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP verboseSEXP, SEXP store_ZSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP symmetrizeSEXP, SEXP project_spdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type store_Z(store_ZSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< std::string >::type symmetrize(symmetrizeSEXP);
    Rcpp::traits::input_parameter< bool >::type project_spd(project_spdSEXP);
    rcpp_result_gen = Rcpp::wrap(ghs_missing_gibbs_cpp(Y, n_iter, burnin, thin, verbose, store_Z, a0, b0, symmetrize, project_spd));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_censored_GHS_cpp2
List gibbs_censored_GHS_cpp2(const arma::mat& Ytilde, const arma::vec& cvec, int n_iter, int burn, int thin, double a0, double b0, std::string symmetrize, bool project_spd, bool verbose, std::string right_or_left);
RcppExport SEXP _ghscenmis_gibbs_censored_GHS_cpp2(SEXP YtildeSEXP, SEXP cvecSEXP, SEXP n_iterSEXP, SEXP burnSEXP, SEXP thinSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP symmetrizeSEXP, SEXP project_spdSEXP, SEXP verboseSEXP, SEXP right_or_leftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ytilde(YtildeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type cvec(cvecSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< std::string >::type symmetrize(symmetrizeSEXP);
    Rcpp::traits::input_parameter< bool >::type project_spd(project_spdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< std::string >::type right_or_left(right_or_leftSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_censored_GHS_cpp2(Ytilde, cvec, n_iter, burn, thin, a0, b0, symmetrize, project_spd, verbose, right_or_left));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ghscenmis_ghs_missing_gibbs_cpp", (DL_FUNC) &_ghscenmis_ghs_missing_gibbs_cpp, 10},
    {"_ghscenmis_gibbs_censored_GHS_cpp2", (DL_FUNC) &_ghscenmis_gibbs_censored_GHS_cpp2, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_ghscenmis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
