# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ghs_missing_gibbs_cpp <- function(Y, n_iter = 3000L, burnin = 1000L, thin = 5L, verbose = TRUE, store_Z = FALSE, a0 = 1e-2, b0 = 1e-2, symmetrize = "average", project_spd = FALSE) {
    .Call('_ghscenmis_ghs_missing_gibbs_cpp', PACKAGE = 'ghscenmis', Y, n_iter, burnin, thin, verbose, store_Z, a0, b0, symmetrize, project_spd)
}

gibbs_censored_GHS_cpp2 <- function(Ytilde, cvec, n_iter = 2000L, burn = 1000L, thin = 1L, a0 = 1e-2, b0 = 1e-2, symmetrize = "average", project_spd = FALSE, verbose = TRUE, right_or_left = "left") {
    .Call('_ghscenmis_gibbs_censored_GHS_cpp2', PACKAGE = 'ghscenmis', Ytilde, cvec, n_iter, burn, thin, a0, b0, symmetrize, project_spd, verbose, right_or_left)
}

